include: firmware: imx: use EOPNOTSUPP instead of ENOTSUP
commit 217f2f95aadbf8247c7d31be2d5c6741ee0c02e6 from
https://github.com/nxp-imx/linux-imx

Linux kernel does not define ENOTSUP, let's use EOPNOTSUPP

The patch fixes the following build break when use imx_v7_defconfig

include/linux/firmware/imx/svc/rm.h: In function ‘imx_sc_rm_find_memreg’:
include/linux/firmware/imx/svc/rm.h:79:10: error: ‘ENOTSUP’ undeclared (first use in this function)
  return -ENOTSUP;
          ^
include/linux/firmware/imx/svc/rm.h:79:10: note: each undeclared identifier is reported only once for each function it appears in
include/linux/firmware/imx/svc/rm.h: In function ‘imx_sc_rm_get_resource_owner’:
include/linux/firmware/imx/svc/rm.h:85:10: error: ‘ENOTSUP’ undeclared (first use in this function)
  return -ENOTSUP;
          ^
include/linux/firmware/imx/svc/rm.h: In function ‘imx_sc_rm_set_memreg_permissions’:
include/linux/firmware/imx/svc/rm.h:92:10: error: ‘ENOTSUP’ undeclared (first use in this function)
  return -ENOTSUP;
          ^
include/linux/firmware/imx/svc/rm.h: In function ‘imx_sc_rm_get_did’:
include/linux/firmware/imx/svc/rm.h:98:10: error: ‘ENOTSUP’ undeclared (first use in this function)
  return -ENOTSUP;
          ^

include/linux/firmware/imx/svc/seco.h: In function ‘imx_sc_seco_build_info’:
include/linux/firmware/imx/svc/seco.h:37:10: error: ‘ENOTSUP’ undeclared (first use in this function)
  return -ENOTSUP;
          ^
include/linux/firmware/imx/svc/seco.h: In function ‘imx_sc_seco_sab_msg’:
include/linux/firmware/imx/svc/seco.h:43:10: error: ‘ENOTSUP’ undeclared (first use in this function)
  return -ENOTSUP;

Fixes: 10237c7bcb174bcc("LF-824: fw: imx: scu: Add missing APIs") and
Fixes: 9edf1255f89b9351("LF-824: fw: imx: scu: Add SECO API")

Reviewed-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Jason Liu <jason.hui.liu@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>