pwm: adp5585: Add return value to pwm_adp5585_get_state()
commit 547cc8dae247 ("pwm: Make .get_state() callback return an error code")
has added a return value to get_state(), so modify and add a return value
to avoid build errors.

error: initialization of 'int (*)(struct pwm_chip *, struct pwm_device *, struct pwm_state *)' from incompatible pointer type 'void (*)(struct pwm_chip *, struct pwm_device *, struct pwm_state *)' [-Werror= incompatible-pointer-types]
   170 | .get_state = pwm_adp5585_get_state,
E
       | ^~~~~~~~~~~~~~~~~~~~~

Fixes: 547cc8dae247 ("pwm: Make .get_state() callback return an error code")
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>