gpu: bridge: cadence: fix build error caused by HDCP helpers change
commit f827a859a803178ad155f0fd38d95b330499c465 from
https://github.com/nxp-imx/linux-imx

API changes since:
6a99099fe1d6 ("drm/display: Move HDCP helpers into display-helper module")

aarch64-poky-linux-ld: drivers/gpu/drm/bridge/cadence/cdns-hdmi-core.o: in function `cdns_hdmi_bridge_attach':
cdns-hdmi-core.c:(.text+0x494): undefined reference to `drm_connector_attach_content_protection_property'
aarch64-poky-linux-ld: drivers/gpu/drm/bridge/cadence/cdns-dp-core.o: in function `cdns_dp_bridge_attach':
cdns-dp-core.c:(.text+0x5c0): undefined reference to `drm_connector_attach_content_protection_property'
aarch64-poky-linux-ld: drivers/gpu/drm/bridge/cadence/cdns-hdcp-common.o: in function `cdns_hdcp_prop_work':
cdns-hdcp-common.c:(.text+0x71c): undefined reference to `drm_hdcp_update_content_protection'
aarch64-poky-linux-ld: drivers/gpu/drm/bridge/cadence/cdns-hdcp-common.o: in function `cdns_hdcp_check_receviers':
cdns-hdcp-common.c:(.text.unlikely+0x398): undefined reference to `drm_hdcp_check_ksvs_revoked'
make[1]: *** [/home/b29396/linux/linux-nxp-rebase/Makefile:1250: vmlinux] Error 1

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>