phy: lynx-28g: drop redefined macro definitions and functions
Previous commit 2d37482e0bed(phy: lynx-28g: add support for backplane modes
through PHY_MODE_ETHERNET_LINKMODE) added redefined macros and function definitions,
This causes below building issues:
drivers/phy/freescale/phy-fsl-lynx-28g.c:1523:13: error: redefinition of 'lynx_28g_remove'
|  1523 | static void lynx_28g_remove(struct platform_device *pdev)
|       |             ^~~~~~~~~~~~~~~
drivers/phy/freescale/phy-fsl-lynx-28g.c:443:6: error: redeclaration of 'enum lynx_28g_eq_type'
|   443 | enum lynx_28g_eq_type {
|       |      ^~~~~~~~~~~~~~~~

And move the static function lynx_28g_snapshot_rx_eq_gains() to before
use.

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>