net: phy: let PHYLINK select MII
Commit bcc096af4de0e3(net: phylink: add support for managed = "c73")
introduces the linkmode_support_c73(), which is defined in the
drivers/net/mii.c, so select Mii. To avoid below building issue:
| aarch64-wrs-linux-ld.bfd: drivers/net/phy/phylink.o: in function `phylink_validate_mac_and_pcs':
| phylink.c:(.text+0x31b4): undefined reference to `linkmode_support_c73'
| aarch64-wrs-linux-ld.bfd: drivers/net/phy/phylink.o: in function `phylink_create':
| phylink.c:(.text+0x37ac): undefined reference to `linkmode_support_c73'

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>