LF-1011-27 arm: imx: pm-imx7ulp: fix build break when calling of_flat_dt_match
commit e952a15e88b93ce9bd6828744a5eb51339f56109 from
https://github.com/nxp-imx/linux-imx

Old API was hiddened from user.

../arch/arm/mach-imx/pm-imx7ulp.c: In function ‘imx7ulp_dt_find_lpsram’:
../arch/arm/mach-imx/pm-imx7ulp.c:559:6: error: implicit declaration of function ‘of_flat_dt_match’ [-Werror=implicit-function-declaration]
  559 |  if (of_flat_dt_match(node, low_power_ocram_match)) {
      |      ^~~~~~~~~~~~~~~~

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>