net: stmmac: add fpe config parameter to fix build error
Because commit ed7e211b6786 ("net: stmmac: fix FPE events losing")
adds the fpe_cfg parameter, add it to avoid below building error.
error: too few arguments to function 'priv->hw->mac->fpe_send_mpacket'

Signed-off-by: Meng Li <Meng.Li@windriver.com>