LF-1162-3: clk: imx: imx8mm: add back required clk.h headfile
commit e6ca365ccaf22cbcf22b78f3a2646fdef0bfc80d from
https://github.com/nxp-imx/linux-imx

Otherwise meet below build break:
../drivers/clk/imx/clk-imx8mm.c: In function ‘imx_clk_init_on’:
../drivers/clk/imx/clk-imx8mm.c:313:9: error: implicit declaration of function ‘clk_prepare_enable’ [-Werror=implicit-function-declaration]
  313 |   ret = clk_prepare_enable(clks[array[i]]->clk);
      |         ^~~~~~~~~~~~~~~~~~
  AR      drivers/clk/mvebu/built-in.a

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>