LF-6810-02: media: Mixel CSI2: fix build error due to API renamed
commit 0a7d32d6b46124557a00063a5987ecbc643ccf6f from
https://github.com/nxp-imx/linux-imx

drivers/staging/media/imx/imx8-mipi-csi2.c:595:46:
error: implicit declaration of function ‘media_entity_remote_pad’; did you mean ‘media_entity_remove_links’? [-Werror=implicit-function-declaration]

(b2e44430b634 media: mc-entity: Rename media_entity_remote_pad() to
 media_pad_remote_pad_first())

Signed-off-by: Guoniu.zhou <guoniu.zhou@nxp.com>
Reviewed-by: Robby Cai <Robby.Cai@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>