LF-1197-1 clk: imx: remove the unused IMX7D_PXP_CLK definition
commit de12dcdad6e2884f042010d4f472b63dfc670967 from
https://github.com/nxp-imx/linux-imx

../drivers/clk/imx/clk-imx7d.c:794:6: error: ‘IMX7D_PXP_CLK’ undeclared (first use in this function); did you mean ‘IMX7D_OCOTP_CLK’?
  794 |  hws[IMX7D_PXP_CLK] = imx_clk_hw_gate4("pxp_clk", "main_axi_root_clk", base + 0x44c0, 0);
      |      ^~~~~~~~~~~~~

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>