LF-1162-6: clk: imx: imx8mq: add back required clk.h headfile
commit b5a7034566dc9054fd80d80e7e1ec7d8c34b191d from
https://github.com/nxp-imx/linux-imx

Otherwise meet below build break:
  CC      drivers/char/mem.o
../drivers/clk/imx/clk-imx8mq.c: In function ‘imx_clk_init_on’:
../drivers/clk/imx/clk-imx8mq.c:296:9: error: implicit declaration of function ‘clk_prepare_enable’ [-Werror=implicit-function-declaration]
  296 |   ret = clk_prepare_enable(clks[array[i]]->clk);

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>