ASoC: fsl: Fix 'pdev' undeclared error in fsl_easrc_hw_params()
The wrong reference of 'pdev' is a typo introduced by commit
93b5b0248d52 ("MLK-21940-4: ASoC: fsl_easrc: Support the m2m function").
We should use 'dev' here.
sound/soc/fsl/fsl_easrc.c: In function 'fsl_easrc_hw_params':
sound/soc/fsl/fsl_easrc.c:1515:26: error: 'pdev' undeclared (first use in this function); did you mean 'dev'?
 1515 |                 dev_err(&pdev->dev, "failed to init m2m device %d\n", ret);
      |                          ^~~~

Signed-off-by: Kevin Hao <kexin.hao@windriver.com>