MGS-4530-2 disable busfreq-imx to fix L4.19 dash build
commit 599b602cb295169de66b1bd40e1a6a4daef73d39 from
https://github.com/nxp-imx/linux-imx

gc_hal_kernel_platform_imx.c:90:14: fatal error: linux/busfreq-imx.h: No such file or directory
 #    include <linux/busfreq-imx.h>

Signed-off-by: Xianzhong <xianzhong.li@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>